#!/usr/bin/Rscript

# A helper function, and Mum's colour scheme -----------------------------------

# This function extracts the digit in a number's 'tens column'. E.g. 4 returns
# 0, 60 returns 6.
tens_col <- function(x) {
  x <- formatC(x, width = 2, flag = "0")
  substr(x, nchar(x) - 1, nchar(x) - 1)
}

# Colours taken from the Facebook post
mum_cols <- c("#7F7F7F", "#FBCC0C", "#4351D6", "#F01E21", "#00A5E5", "#FFEE0B",
              "#17BD4F", "#A646A7", "#B4E615", "#FC8123")

# A function to manipulate matricies, and plot results -------------------------

# The plotting function. This accepts the 'to' and 'from' numbers for the times
# tables, a function to apply to the numbers, and a vector of colours to
# represent the numbers generated by 'fun'
plot_matrix <- function(n1 = 1, n2 = 35, fun = tens_col, colours = mum_cols) {
  a <- matrix(rep(c(n1:n2, n2:n1), each = n2 * 2), ncol = n2 * 2)
  m <- tens_col(a * t(a))
  class(m) <- "numeric"
  par(mar = rep(0, 4))
  image(m, col = mum_cols, xaxt = "n", yaxt = "n")
}

# Make a GIF -------------------------------------------------------------------

library(animation)
n_frames <- 150

saveGIF({
  for (i in 3:n_frames) {
    plot_matrix(1, i)
  }
}, movie.name = "mothers_matrix_masterpiece.gif", interval = 0.25
)
